[package]
name = "rbperf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.5.1"
anyhow = "1.0.57"
proc-maps = "0.2.1"
serde = { version = "1.0.137", features = ["derive"] }
bcc = "0.0.32"
clap = "3.1.17"
serde_json = "1.0.81"
chrono = "0.4.19"
inferno = "0.11.2"
libbpf-rs = "0.17.0"
perf-event-open-sys = "1.0.1"
errno = "0.2.8"
libc = "0.2.125"
rand = "*"
nix = "*"
project-root = "0.2.2"
log = "0.4.17"
env_logger = "0.9.0"

[build-dependencies]
bindgen = "0.59.2"
libbpf-cargo = "0.11.0"
