[package]
name = "rbperf"
description = "Sampling profiler and tracer for Ruby (CRuby) which runs in BPF"
version = "0.1.0-beta"
repository = "https://github.com/javierhonduco/rbperf"
authors = ["Javier Honduvilla Coto <javierhonduco@gmail.com>"]
keywords = ["bpf", "ebpf", "ruby", "CRuby", "profiler", "tracer"]
license = "MIT"
edition = "2021"

[dependencies]
goblin = "0.5.1"
anyhow = {version= "1.0.57", features = ["backtrace"]}
proc-maps = "0.2.1"
serde = { version = "1.0.137", features = ["derive"] }
clap = "3.1.17"
serde_json = "1.0.81"
chrono = "0.4.19"
inferno = "0.11.2"
libbpf-rs = { version = "0.17.0", git = "https://github.com/javierhonduco/libbpf-rs", branch = "libelf-zlib-static", features=["static"]}
perf-event-open-sys = "1.0.1"
errno = "0.2.8"
libc = "0.2.125"
log = "0.4.17"
env_logger = "0.9.0"
serde_yaml = "0.8"

[dev-dependencies]
nix = "0.23.1"
project-root = "0.2.2"
rand = "0.8.5"
scopeguard = "1.1.0"

[build-dependencies]
bindgen = "0.59.2"
libbpf-cargo = { version = "0.11.0", git = "https://github.com/javierhonduco/libbpf-rs", branch = "libelf-zlib-static"}