[package]
name = "rbperf"
description = "Sampling profiler and tracer for Ruby (CRuby) which runs in BPF"
version = "0.2.0"
repository = "https://github.com/javierhonduco/rbperf"
authors = ["Javier Honduvilla Coto <javierhonduco@gmail.com>"]
keywords = ["bpf", "ebpf", "ruby", "CRuby", "profiler", "tracer"]
license = "MIT"
edition = "2021"

[dependencies]
goblin = "0.5.4"
anyhow = {version= "1.0.65", features = ["backtrace"]}
proc-maps = "0.2.1"
serde = { version = "1.0.145", features = ["derive"] }
clap = "3.2.22"
serde_json = "1.0.85"
chrono = "0.4.22"
inferno = "0.11.9"
libbpf-rs = { git = "https://github.com/libbpf/libbpf-rs", branch = "master", features=["static"]}
perf-event-open-sys = "3.0.0"
errno = "0.2.8"
libc = "0.2.134"
log = "0.4.17"
env_logger = "0.9.1"
serde_yaml = "0.9"
thiserror = "1.0.37"
nix = "0.25.0"
syscalls = { version = "0.6", default-features = false }
ctrlc = "3.2.3"

[dev-dependencies]
project-root = "0.2.2"
rand = "0.8.5"

[build-dependencies]
bindgen = "0.60.1"
libbpf-cargo = { git = "https://github.com/libbpf/libbpf-rs", branch = "master"}

[workspace]
members = [
    ".",
    "xtask",
]
