[package]
name = "rbperf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.5.1"
anyhow = "1.0.57"
proc-maps = "0.2.1"
serde = { version = "1.0.137", features = ["derive"] }
bcc = "0.0.32"

[build-dependencies]
bindgen = "0.59.2"
