# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rbperf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rbperf.proto',
  package='rbperf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0crbperf.proto\x12\x06rbperf\"\xcf\x02\n\x07Profile\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.rbperf.Profile.Type\x12\x12\n\ncreated_at\x18\x04 \x01(\x05\x12\x10\n\x08hostname\x18\x05 \x01(\t\x12\x15\n\rkernel_string\x18\x06 \x01(\t\x12\x16\n\x0erbperf_version\x18\x07 \x01(\t\x12\'\n\x0bstacktraces\x18\x08 \x03(\x0b\x32\x12.rbperf.StackTrace\x12\x36\n\x0cstring_table\x18\t \x03(\x0b\x32 .rbperf.Profile.StringTableEntry\x1a\x32\n\x10StringTableEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"6\n\x04Type\x12\x08\n\x04PERF\x10\x00\x12\x0e\n\nTRACEPOINT\x10\x01\x12\n\n\x06UPROBE\x10\x02\x12\x08\n\x04USDT\x10\x03\"5\n\x05\x46rame\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0e\n\x06lineno\x18\x03 \x01(\x05\"=\n\rInternedFrame\x12\x0c\n\x04path\x18\x01 \x01(\x05\x12\x0e\n\x06method\x18\x02 \x01(\x05\x12\x0e\n\x06lineno\x18\x03 \x01(\x05\"\x86\x02\n\nStackTrace\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0b\n\x03tid\x18\x02 \x01(\x05\x12\x0b\n\x03\x63pu\x18\x03 \x01(\x05\x12\x0b\n\x03pid\x18\x04 \x01(\x05\x12\x0c\n\x04\x63omm\x18\x05 \x01(\t\x12\x34\n\x0cstack_status\x18\x06 \x01(\x0e\x32\x1e.rbperf.StackTrace.StackStatus\x12\x1d\n\x06\x66rames\x18\x07 \x03(\x0b\x32\r.rbperf.Frame\x12.\n\x0finterned_frames\x18\x08 \x03(\x0b\x32\x15.rbperf.InternedFrame\"+\n\x0bStackStatus\x12\x0c\n\x08\x43OMPLETE\x10\x00\x12\x0e\n\nINCOMPLETE\x10\x01*)\n\x0bStorageType\x12\r\n\tSTREAMING\x10\x00\x12\x0b\n\x07\x43OMPACT\x10\x01\x62\x06proto3')
)

_STORAGETYPE = _descriptor.EnumDescriptor(
  name='StorageType',
  full_name='rbperf.StorageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STREAMING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPACT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=745,
  serialized_end=786,
)
_sym_db.RegisterEnumDescriptor(_STORAGETYPE)

StorageType = enum_type_wrapper.EnumTypeWrapper(_STORAGETYPE)
STREAMING = 0
COMPACT = 1


_PROFILE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='rbperf.Profile.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PERF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRACEPOINT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPROBE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USDT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=306,
  serialized_end=360,
)
_sym_db.RegisterEnumDescriptor(_PROFILE_TYPE)

_STACKTRACE_STACKSTATUS = _descriptor.EnumDescriptor(
  name='StackStatus',
  full_name='rbperf.StackTrace.StackStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCOMPLETE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=700,
  serialized_end=743,
)
_sym_db.RegisterEnumDescriptor(_STACKTRACE_STACKSTATUS)


_PROFILE_STRINGTABLEENTRY = _descriptor.Descriptor(
  name='StringTableEntry',
  full_name='rbperf.Profile.StringTableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rbperf.Profile.StringTableEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rbperf.Profile.StringTableEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=304,
)

_PROFILE = _descriptor.Descriptor(
  name='Profile',
  full_name='rbperf.Profile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rbperf.Profile.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='rbperf.Profile.created_at', index=1,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='rbperf.Profile.hostname', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kernel_string', full_name='rbperf.Profile.kernel_string', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rbperf_version', full_name='rbperf.Profile.rbperf_version', index=4,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stacktraces', full_name='rbperf.Profile.stacktraces', index=5,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_table', full_name='rbperf.Profile.string_table', index=6,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROFILE_STRINGTABLEENTRY, ],
  enum_types=[
    _PROFILE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=360,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='rbperf.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='rbperf.Frame.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='rbperf.Frame.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lineno', full_name='rbperf.Frame.lineno', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=415,
)


_INTERNEDFRAME = _descriptor.Descriptor(
  name='InternedFrame',
  full_name='rbperf.InternedFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='rbperf.InternedFrame.path', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='rbperf.InternedFrame.method', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lineno', full_name='rbperf.InternedFrame.lineno', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=478,
)


_STACKTRACE = _descriptor.Descriptor(
  name='StackTrace',
  full_name='rbperf.StackTrace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rbperf.StackTrace.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tid', full_name='rbperf.StackTrace.tid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu', full_name='rbperf.StackTrace.cpu', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='rbperf.StackTrace.pid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comm', full_name='rbperf.StackTrace.comm', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stack_status', full_name='rbperf.StackTrace.stack_status', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frames', full_name='rbperf.StackTrace.frames', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interned_frames', full_name='rbperf.StackTrace.interned_frames', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STACKTRACE_STACKSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=743,
)

_PROFILE_STRINGTABLEENTRY.containing_type = _PROFILE
_PROFILE.fields_by_name['type'].enum_type = _PROFILE_TYPE
_PROFILE.fields_by_name['stacktraces'].message_type = _STACKTRACE
_PROFILE.fields_by_name['string_table'].message_type = _PROFILE_STRINGTABLEENTRY
_PROFILE_TYPE.containing_type = _PROFILE
_STACKTRACE.fields_by_name['stack_status'].enum_type = _STACKTRACE_STACKSTATUS
_STACKTRACE.fields_by_name['frames'].message_type = _FRAME
_STACKTRACE.fields_by_name['interned_frames'].message_type = _INTERNEDFRAME
_STACKTRACE_STACKSTATUS.containing_type = _STACKTRACE
DESCRIPTOR.message_types_by_name['Profile'] = _PROFILE
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['InternedFrame'] = _INTERNEDFRAME
DESCRIPTOR.message_types_by_name['StackTrace'] = _STACKTRACE
DESCRIPTOR.enum_types_by_name['StorageType'] = _STORAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Profile = _reflection.GeneratedProtocolMessageType('Profile', (_message.Message,), dict(

  StringTableEntry = _reflection.GeneratedProtocolMessageType('StringTableEntry', (_message.Message,), dict(
    DESCRIPTOR = _PROFILE_STRINGTABLEENTRY,
    __module__ = 'rbperf_pb2'
    # @@protoc_insertion_point(class_scope:rbperf.Profile.StringTableEntry)
    ))
  ,
  DESCRIPTOR = _PROFILE,
  __module__ = 'rbperf_pb2'
  # @@protoc_insertion_point(class_scope:rbperf.Profile)
  ))
_sym_db.RegisterMessage(Profile)
_sym_db.RegisterMessage(Profile.StringTableEntry)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(
  DESCRIPTOR = _FRAME,
  __module__ = 'rbperf_pb2'
  # @@protoc_insertion_point(class_scope:rbperf.Frame)
  ))
_sym_db.RegisterMessage(Frame)

InternedFrame = _reflection.GeneratedProtocolMessageType('InternedFrame', (_message.Message,), dict(
  DESCRIPTOR = _INTERNEDFRAME,
  __module__ = 'rbperf_pb2'
  # @@protoc_insertion_point(class_scope:rbperf.InternedFrame)
  ))
_sym_db.RegisterMessage(InternedFrame)

StackTrace = _reflection.GeneratedProtocolMessageType('StackTrace', (_message.Message,), dict(
  DESCRIPTOR = _STACKTRACE,
  __module__ = 'rbperf_pb2'
  # @@protoc_insertion_point(class_scope:rbperf.StackTrace)
  ))
_sym_db.RegisterMessage(StackTrace)


_PROFILE_STRINGTABLEENTRY._options = None
# @@protoc_insertion_point(module_scope)
